"""
Data utility constants
"""
import os, cPickle

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data")
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data", "parsed")

SYMBOL_MAPPING = {
    "ac": "actinium",
    "al": "aluminum",
    "am": "americium",
    "sb": "antimony",
    "ar": "argon",
    "as": "arsenic",
    "at": "astatine",
    "ba": "barium",
    "bk": "berkelium",
    "be": "beryllium",
    "bi": "bismuth",
    "bh": "bohrium",
    "b": "boron",
    "br": "bromine",
    "cd": "cadmium",
    "cs": "cesium",
    "ca": "calcium",
    "cf": "californium",
    "c": "carbon",
    "ce": "cerium",
    "cl": "chlorine",
    "cn": "copernicium",
    "cr": "chromium",
    "co": "cobalt",
    "cu": "copper",
    "cm": "curium",
    "ds": "darmstadtium",
    "db": "dubnium",
    "dy": "dysprosium",
    "es": "einsteinium",
    "er": "erbium",
    "eu": "europium",
    "fm": "fermium",
    "f": "fluorine",
    "fl": "flerovium",
    "fr": "francium",
    "gd": "gadolinium",
    "ga": "gallium",
    "ge": "germanium",
    "au": "gold",
    "hf": "hafnium",
    "hs": "hassium",
    "he": "helium",
    "ho": "holmium",
    "h": "hydrogen",
    "in": "indium",
    "i": "iodine",
    "ir": "iridium",
    "fe": "iron",
    "kr": "krypton",
    "la": "lanthanum",
    "lr": "lawrencium",
    "lv": "livermorium",
    "pb": "lead",
    "li": "lithium",
    "lu": "lutetium",
    "mg": "magnesium",
    "mn": "manganese",
    "mt": "meitnerium",
    "md": "mendelevium",
    "hg": "mercury",
    "mo": "molybdenum",
    "nd": "neodymium",
    "ne": "neon",
    "np": "neptunium",
    "ni": "nickel",
    "nb": "niobium",
    "n": "nitrogen",
    "no": "nobelium",
    "os": "osmium",
    "o": "oxygen",
    "pd": "palladium",
    "p": "phosphorus",
    "pt": "platinum",
    "pu": "plutonium",
    "po": "polonium",
    "k": "potassium",
    "pr": "praseodymium",
    "pm": "promethium",
    "pa": "protactinium",
    "ra": "radium",
    "rn": "radon",
    "re": "rhenium",
    "rh": "rhodium",
    "rg": "roentgenium",
    "rb": "rubidium",
    "ru": "ruthenium",
    "rf": "rutherfordium",
    "sm": "samarium",
    "sc": "scandium",
    "sg": "seaborgium",
    "se": "selenium",
    "si": "silicon",
    "ag": "silver",
    "na": "sodium",
    "sr": "strontium",
    "s": "sulfur",
    "ta": "tantalum",
    "tc": "technetium",
    "te": "tellurium",
    "tb": "terbium",
    "tl": "thallium",
    "th": "thorium",
    "tm": "thulium",
    "sn": "tin",
    "ti": "titanium",
    "w": "tungsten",
    "uub": "ununbium",
    "uuh": "ununhexium",
    "uuo": "ununoctium",
    "uup": "ununpentium",
    "uuq": "ununquadium",
    "uus": "ununseptium",
    "uut": "ununtrium",
    "u": "uranium",
    "v": "vanadium",
    "xe": "xenon",
    "yb": "ytterbium",
    "y": "yttrium",
    "zn": "zinc",
    "zr": "zirconium"
}
ELEMENT_MAPPING = dict((value, key) for key, value in SYMBOL_MAPPING.iteritems())
ELEMENT_MAPPING["aluminium"] = "al"

def cache(data, filename):
    dirname = os.path.dirname(filename)
    if not os.path.exists(dirname):
        os.makedirs(dirname)
    cPickle.dump(data, open(filename, 'wb'))


def load(filename):
    if not os.path.exists(filename):
        return None
    with open(filename, 'rb') as f:
        return cPickle.load(f)
