"""
Data utility constants
"""
import os, cPickle

DATA_DIR = os.path.abspath("../../data")
OUTPUT_DIR = os.path.abspath("../../data/parsed")

SYMBOL_MAPPING = {
    "Ac": "Actinium",
    "Al": "Aluminum",
    "Am": "Americium",
    "Sb": "Antimony",
    "Ar": "Argon",
    "As": "Arsenic",
    "At": "Astatine",
    "Ba": "Barium",
    "Bk": "Berkelium",
    "Be": "Beryllium",
    "Bi": "Bismuth",
    "Bh": "Bohrium",
    "B": "Boron",
    "Br": "Bromine",
    "Cd": "Cadmium",
    "Cs": "Cesium",
    "Ca": "Calcium",
    "Cf": "Californium",
    "C": "Carbon",
    "Ce": "Cerium",
    "Cl": "Chlorine",
    "Cn": "Copernicium",
    "Cr": "Chromium",
    "Co": "Cobalt",
    "Cu": "Copper",
    "Cm": "Curium",
    "Ds": "Darmstadtium",
    "Db": "Dubnium",
    "Dy": "Dysprosium",
    "Es": "Einsteinium",
    "Er": "Erbium",
    "Eu": "Europium",
    "Fm": "Fermium",
    "F": "Fluorine",
    "Fl": "Flerovium",
    "Fr": "Francium",
    "Gd": "Gadolinium",
    "Ga": "Gallium",
    "Ge": "Germanium",
    "Au": "Gold",
    "Hf": "Hafnium",
    "Hs": "Hassium",
    "He": "Helium",
    "Ho": "Holmium",
    "H": "Hydrogen",
    "In": "Indium",
    "I": "Iodine",
    "Ir": "Iridium",
    "Fe": "Iron",
    "Kr": "Krypton",
    "La": "Lanthanum",
    "Lr": "Lawrencium",
    "Lv": "Livermorium",
    "Pb": "Lead",
    "Li": "Lithium",
    "Lu": "Lutetium",
    "Mg": "Magnesium",
    "Mn": "Manganese",
    "Mt": "Meitnerium",
    "Md": "Mendelevium",
    "Hg": "Mercury",
    "Mo": "Molybdenum",
    "Nd": "Neodymium",
    "Ne": "Neon",
    "Np": "Neptunium",
    "Ni": "Nickel",
    "Nb": "Niobium",
    "N": "Nitrogen",
    "No": "Nobelium",
    "Os": "Osmium",
    "O": "Oxygen",
    "Pd": "Palladium",
    "P": "Phosphorus",
    "Pt": "Platinum",
    "Pu": "Plutonium",
    "Po": "Polonium",
    "K": "Potassium",
    "Pr": "Praseodymium",
    "Pm": "Promethium",
    "Pa": "Protactinium",
    "Ra": "Radium",
    "Rn": "Radon",
    "Re": "Rhenium",
    "Rh": "Rhodium",
    "Rg": "Roentgenium",
    "Rb": "Rubidium",
    "Ru": "Ruthenium",
    "Rf": "Rutherfordium",
    "Sm": "Samarium",
    "Sc": "Scandium",
    "Sg": "Seaborgium",
    "Se": "Selenium",
    "Si": "Silicon",
    "Ag": "Silver",
    "Na": "Sodium",
    "Sr": "Strontium",
    "S": "Sulfur",
    "Ta": "Tantalum",
    "Tc": "Technetium",
    "Te": "Tellurium",
    "Tb": "Terbium",
    "Tl": "Thallium",
    "Th": "Thorium",
    "Tm": "Thulium",
    "Sn": "Tin",
    "Ti": "Titanium",
    "W": "Tungsten",
    "Uub": "Ununbium",
    "Uuh": "Ununhexium",
    "Uuo": "Ununoctium",
    "Uup": "Ununpentium",
    "Uuq": "Ununquadium",
    "Uus": "Ununseptium",
    "Uut": "Ununtrium",
    "U": "Uranium",
    "V": "Vanadium",
    "Xe": "Xenon",
    "Yb": "Ytterbium",
    "Y": "Yttrium",
    "Zn": "Zinc",
    "Zr": "Zirconium"
}
ELEMENT_MAPPING = dict((value, key) for key, value in SYMBOL_MAPPING.iteritems())
ELEMENT_MAPPING["Aluminium"] = "Al"

def cache(data, filename):
    dirname = os.path.dirname(filename)
    if not os.path.exists(dirname):
        os.makedirs(dirname)
    cPickle.dump(data, open(filename, 'wb'))
